apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 931162420686.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 931162420686.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: f362502e
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
